/* ==========================================================================
   博客文章数据
   修改这里即可新增 / 编辑文章。
   content 字段使用 Markdown 语法，用数组按行书写（避免转义问题）。
   支持的语法：# ~ #### 标题、``` 代码块、> 引用、- / 1. 列表、
                `行内代码`、**加粗**、*斜体*、[链接](url)
   ========================================================================== */

const md = (lines) => lines.join('\n');

const posts = [
  {
    id: 1,
    title: '从零搭建个人技术博客：原生 HTML/CSS/JS 实战',
    date: '2026-09-10',
    readTime: '6 分钟',
    tags: ['HTML', 'CSS', 'JavaScript'],
    excerpt: '不用任何框架和构建工具，只用三样东西搭一个能跑、能看、能改的博客，顺便把前端基础串起来。',
    content: md([
      '## 为什么还要自己写博客？',
      '',
      '很多人会问：都有掘金、知乎、公众号了，为什么还要自己搭一个？我的答案是：**一个完全属于自己的空间，写作更自由，也更能沉淀技术**。',
      '',
      '更重要的是，亲手搭建一个博客本身就是一次很好的实践——从零理解 HTML、CSS、JavaScript 是如何协作的。',
      '',
      '## 技术选型：只用了三样东西',
      '',
      '- HTML5：语义化标签，搭建页面骨架',
      '- CSS3：变量、Flexbox、Grid，负责样式与响应式',
      '- JavaScript：渲染文章、筛选标签、切换主题',
      '',
      '没有框架，没有构建工具，双击 `index.html` 就能跑起来。',
      '',
      '## 核心思路',
      '',
      '1. 把文章数据存在 JS 数组里',
      '2. 用 JS 渲染文章列表与详情',
      '3. 通过 hash 路由实现"页面"切换',
      '',
      '```js',
      'const posts = [',
      '  { id: 1, title: "Hello", tags: ["JS"] }',
      '];',
      '',
      'function render(list) {',
      '  return list.map(p => `<a href="#/post/${p.id}">${p.title}</a>`).join("");',
      '}',
      '```',
      '',
      '> 提示：这种"数据 + 模板渲染"的思路，其实就是现代前端框架的雏形。',
      '',
      '## 总结',
      '',
      '静态博客足够轻量、足够快，配合 GitHub Pages 就能免费上线。动手写一个，你对前端的理解会更深一层。'
    ])
  },
  {
    id: 2,
    title: 'JavaScript 异步编程：从回调地狱到 async/await',
    date: '2026-08-28',
    readTime: '8 分钟',
    tags: ['JavaScript', '异步'],
    excerpt: '依次读取三个文件这个简单需求，如何从层层嵌套的回调，一路演进到像同步代码一样清晰的 async/await。',
    content: md([
      '## 从一个需求说起',
      '',
      '假设我们要依次读取三个文件。最早我们只能写回调：',
      '',
      '```js',
      'fs.readFile("a.txt", (err, data) => {',
      '  fs.readFile("b.txt", (err, data) => {',
      '    fs.readFile("c.txt", (err, data) => {',
      '      console.log("done");',
      '    });',
      '  });',
      '});',
      '```',
      '',
      '这种层层嵌套的写法被称为**回调地狱**，可读性差、错误处理困难。',
      '',
      '## Promise：把"将来"包起来',
      '',
      'Promise 有三种状态：`pending`（进行中）、`fulfilled`（成功）、`rejected`（失败），状态一旦改变就不可逆。',
      '',
      '```js',
      'function readFile(name) {',
      '  return new Promise((resolve, reject) => {',
      '    fs.readFile(name, (err, data) => err ? reject(err) : resolve(data));',
      '  });',
      '}',
      '',
      'readFile("a.txt")',
      '  .then(() => readFile("b.txt"))',
      '  .then(() => readFile("c.txt"))',
      '  .catch(err => console.error(err));',
      '```',
      '',
      '## async / await：语法糖，但很甜',
      '',
      '`async/await` 让异步代码看起来像同步代码：',
      '',
      '```js',
      'async function main() {',
      '  try {',
      '    await readFile("a.txt");',
      '    await readFile("b.txt");',
      '    await readFile("c.txt");',
      '    console.log("done");',
      '  } catch (err) {',
      '    console.error(err);',
      '  }',
      '}',
      '```',
      '',
      '## 几个容易踩的坑',
      '',
      '- 忘了 `await`，拿到的是 Promise 而不是值',
      '- 在 `forEach` 里用 `await` 不会按顺序等待',
      '- 顶层 `await` 只在 ES 模块里可用',
      '',
      '> 记住：`async` 函数永远返回 Promise，哪怕你没有显式 `return`。'
    ])
  },
  {
    id: 3,
    title: 'CSS 现代布局：Flexbox 与 Grid 到底怎么选',
    date: '2026-08-15',
    readTime: '7 分钟',
    tags: ['CSS', '布局'],
    excerpt: '一句话分清两者：Flexbox 是一维布局，Grid 是二维布局。附典型场景和常见误区。',
    content: md([
      '## Flexbox 与 Grid 的本质区别',
      '',
      '一句话总结：**Flexbox 是一维布局，Grid 是二维布局**。',
      '',
      '- Flexbox：沿着"一个方向"（主轴）排列元素，适合行内或列内的分布',
      '- Grid：同时控制"行和列"，适合整页或卡片网格的结构',
      '',
      '## 什么时候用 Flexbox',
      '',
      '典型场景：导航栏、按钮组、居中对齐、卡片内部排版。',
      '',
      '```css',
      '.navbar {',
      '  display: flex;',
      '  justify-content: space-between;',
      '  align-items: center;',
      '}',
      '```',
      '',
      '## 什么时候用 Grid',
      '',
      '典型场景：响应式卡片墙、仪表盘、整体页面骨架。',
      '',
      '```css',
      '.gallery {',
      '  display: grid;',
      '  grid-template-columns: repeat(auto-fill, minmax(200px, 1fr));',
      '  gap: 16px;',
      '}',
      '```',
      '',
      '`minmax` 配合 `auto-fill`，一行就能实现自适应列数，非常实用。',
      '',
      '## 常见误区',
      '',
      '1. 用 Flexbox 硬撑出两列布局——其实 Grid 更合适',
      '2. 用 Grid 排版单行按钮——杀鸡用牛刀',
      '3. 忽略 `gap` 属性，还在用 margin 手动留白',
      '',
      '> 我的经验法：先问"这是行还是面"？行用 Flex，面用 Grid。'
    ])
  },
  {
    id: 4,
    title: 'Git 常用命令速查与团队协作工作流',
    date: '2026-07-30',
    readTime: '5 分钟',
    tags: ['Git', '工具'],
    excerpt: '把每天都要用的 Git 命令和分支工作流整理成一张速查表，减少手忙脚乱。',
    content: md([
      '## 日常高频命令',
      '',
      '```bash',
      'git status                 # 查看当前状态',
      'git diff                   # 查看未暂存的改动',
      'git add .                  # 暂存所有改动',
      'git commit -m "message"    # 提交',
      'git log --oneline --graph  # 查看提交历史',
      '```',
      '',
      '## 分支工作流',
      '',
      '```bash',
      'git checkout -b feat/login  # 新建并切换到功能分支',
      'git push -u origin feat/login',
      '# 开发完成后合并回主分支',
      'git checkout main',
      'git merge feat/login',
      'git branch -d feat/login    # 删除本地分支',
      '```',
      '',
      '## 撤销与回退',
      '',
      '- `git reset --soft HEAD~1`：撤销提交但保留改动',
      '- `git reset --hard HEAD~1`：撤销提交并丢弃改动（慎用）',
      '- `git revert <commit>`：生成一个新提交来"反做"某次提交',
      '',
      '## 几个好习惯',
      '',
      '1. 提交信息用祈使句：`add` 而不是 `added`',
      '2. 一次提交只做一件事',
      '3. 提交前先 `git diff` 检查一遍',
      '',
      '> 原则：让历史记录像一篇可读的文章，而不是随手记的流水账。'
    ])
  },
  {
    id: 5,
    title: '浏览器渲染原理：从 HTML 到像素',
    date: '2026-07-12',
    readTime: '9 分钟',
    tags: ['浏览器', '原理'],
    excerpt: '了解 DOM、CSSOM、渲染树、回流与重绘，写出更流畅的页面。',
    content: md([
      '## 渲染流水线',
      '',
      '浏览器从拿到 HTML 到显示像素，大致经历五个阶段：',
      '',
      '1. 解析 HTML，构建 DOM 树',
      '2. 解析 CSS，构建 CSSOM 树',
      '3. 二者合成渲染树（Render Tree）',
      '4. 布局（Layout）：计算每个节点的位置和大小',
      '5. 绘制（Paint）：把节点画到屏幕上',
      '',
      '## 回流与重绘',
      '',
      '- **回流（Reflow）**：几何信息变化，需要重新布局，代价高',
      '- **重绘（Repaint）**：只是外观变化，不涉及布局，代价低',
      '',
      '```js',
      '// 触发回流',
      'el.style.width = "200px";',
      '// 触发重绘',
      'el.style.color = "red";',
      '```',
      '',
      '## 减少回流的技巧',
      '',
      '- 批量修改样式，用 `class` 而不是逐个改 `style`',
      '- 动画优先用 `transform` 和 `opacity`，它们只触发合成，不触发布局',
      '- 需要多次读取布局信息时，先缓存变量',
      '',
      '> 理解渲染流程，才能写出流畅的 60fps 页面。'
    ])
  },
  {
    id: 6,
    title: 'Web 性能优化入门：让页面快人一步',
    date: '2026-06-25',
    readTime: '6 分钟',
    tags: ['性能', '前端'],
    excerpt: '先测量再优化：图片、字体、加载策略，以及 LCP / INP / CLS 三大核心指标。',
    content: md([
      '## 先测量，再优化',
      '',
      '优化前先用 Lighthouse 或浏览器 Performance 面板跑一遍，找到真正的瓶颈，别凭感觉瞎调。',
      '',
      '## 资源优化',
      '',
      '- 图片：用 WebP/AVIF，按需加载 `loading="lazy"`',
      '- 字体：`font-display: swap`，只加载用到的字重',
      '- CSS/JS：合并、压缩，移除没用的代码',
      '',
      '## 加载策略',
      '',
      '```html',
      '<!-- 非关键 JS 延后加载 -->',
      '<script src="analytics.js" defer></script>',
      '',
      '<!-- 图片懒加载 -->',
      '<img src="placeholder.jpg" data-src="real.jpg" loading="lazy" alt="" />',
      '```',
      '',
      '## 关键指标',
      '',
      '1. LCP（最大内容绘制）：衡量加载速度',
      '2. INP（交互延迟）：衡量响应速度',
      '3. CLS（布局偏移）：衡量视觉稳定性',
      '',
      '> 记住：性能优化是"测量 → 优化 → 再测量"的循环，而不是一次性工作。'
    ])
  }
];
